### ISSUE TITLE
Simple Peer Not Found

### ISSUE THREAD

**Issue by devsimsek** [HR/ciphora#12]
App threw an error during load
Error: Cannot find module './simple-peer'
Require stack:
- /somedirectory/ciphora/src/main/lib/Peers.js
- /somedirectory/ciphora/src/main/index.js
- /somedirectory/ciphora/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7718:16)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/somedirectory/ciphora/src/main/lib/Peers.js:15:10)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)

**Comment by devsimsek** [comment]
Oh sorry my bad. I did typo
