### ISSUE TITLE
Error: Cannot find module 'get-browser-rtc'

### ISSUE THREAD

**Issue by zumbata** [HR/ciphora#14]
I follow all the steps in Setup and Run instructions, but I am still getting this error on "**In a new tty, run the app $ gulp**" step:

```
zumbata@zumbata-desktop:~/ciphora$ gulp 
[17:40:41] Using gulpfile ~/ciphora/gulpfile.js
[17:40:41] Starting 'default'...
[17:40:41] Starting 'electron'...
[17:40:41] Finished 'electron' after 3.11 ms
App threw an error during load
Error: Cannot find module 'get-browser-rtc'
Require stack:
- /home/zumbata/ciphora/src/main/lib/simple-peer/index.js
- /home/zumbata/ciphora/src/main/lib/Peers.js
- /home/zumbata/ciphora/src/main/index.js
- /home/zumbata/ciphora/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/zumbata/ciphora/src/main/lib/simple-peer/index.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'get-browser-rtc'
Require stack:
- /home/zumbata/ciphora/src/main/lib/simple-peer/index.js
- /home/zumbata/ciphora/src/main/lib/Peers.js
- /home/zumbata/ciphora/src/main/index.js
- /home/zumbata/ciphora/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/zumbata/ciphora/src/main/lib/simple-peer/index.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

I am attaching the result from "**For faster dev, run the bundler (webpack) $ yarn run bundler**" step too:

```
zumbata@zumbata-desktop:~/ciphora$ yarn run bundler
yarn run v1.22.10
$ BROWSER=none webpack serve --mode development
ℹ ｢wds｣: Project is running at http://localhost:9000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/zumbata/ciphora
ℹ ｢wdm｣: assets by chunk 5.38 MiB (name: main)
  asset app.js 5.3 MiB [emitted] (name: main)
  asset app.css 82.5 KiB [emitted] (name: main)
asset 175f391f238cd7deffa88e420c9b32ff.woff2 49.4 KiB [emitted] [immutable] [from: static/fonts/ionicons.woff2] (auxiliary name: main)
asset ./index.html 324 bytes [emitted]
Entrypoint main 5.38 MiB (49.4 KiB) = app.css 82.5 KiB app.js 5.3 MiB 1 auxiliary asset
runtime modules 1.04 KiB 5 modules
modules by path ./node_modules/ 1.92 MiB 194 modules
modules by path ./src/ 45.3 KiB
  modules by path ./src/renderer/components/*.js 39.4 KiB 13 modules
  modules by path ./src/renderer/lib/*.js 4.44 KiB 2 modules
  ./src/renderer/index.js 1.14 KiB [built] [code generated]
  ./src/consts.js 372 bytes [built] [code generated]
modules by path ./static/scss/*.scss 50 bytes (javascript) 82.5 KiB (css/mini-extract)
  ./static/scss/index.scss 50 bytes [built] [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./static/scss/index.scss 82.5 KiB [code generated]
6 modules
webpack 5.40.0 compiled successfully in 1955 ms
ℹ ｢wdm｣: Compiled successfully.
```

**Comment by HR** [comment]
A lot has changed since this project was made so I'll have to take some time to rejuvenate this project.
