### ISSUE TITLE
the web

### ISSUE THREAD

**Issue by AdrianWangs** [HR/ciphora#16]

**Comment by AdrianWangs** [comment]
when I run the command 'gulp' or 'yarn start' ,there will be a blank window, and it seems that the web server is not running,there are error logs in the console, such as:
```
(node:12457) electron: Failed to load URL: http://localhost:8080/ with error: ERR_CONNECTION_REFUSED
(Use `Electron --trace-warnings ...` to show where the warning was created)
Error: ERR_CONNECTION_REFUSED (-102) loading 'http://localhost:8080/'
    at rejectAndCleanup (electron/js2c/browser_init.js:213:985)
    at Object.failListener (electron/js2c/browser_init.js:213:1198)
    at Object.emit (events.js:315:20) {
  errno: -102,
  code: 'ERR_CONNECTION_REFUSED',
  url: 'http://localhost:8080/'
}
```

**Comment by HR** [comment]
this is a macOS firewall issue, you have to give the app access to your local network. See https://github.com/electron/electron/issues/11882
